# Enabled operations
# Uncomment the ones you want to use by default
operations:
# STT
- role: stt
  id: gemini
  model: models/gemma-3-1b-it
  language: pt-BR
  
  # T2T
# - role: t2t
#   id: kobold
#   max_context_length: 2048
#   max_length: 100
#   quiet: true
#   rep_pen: 1.1
#   rep_pen_range: 256
#   rep_pen_slope: 1
#   temperature: 0.5
#   tfs: 1
#   top_a: 0
#   top_k: 100
#   top_p: 0.9
#   typical: 1
- role: t2t
  id: gemini
  model: models/gemma-3-1b-it # Gemma 3 model for higher limits
  temperature: 1.0 # Slightly reduced for more natural balance
  top_p: 0.95
  max_output_tokens: 8192

  # Text filters
- role: filter_text
  id: filter_clean
# - role: filter_text
#   id: emotion_roberta
# - role: filter_text
#   id: mod_koala
# - role: filter_text
#   id: chunker_sentence

  # TTS
# - role: tts
#   id: azure
#   voice: "en-US-AshleyNeural"
- role: tts
  id: pytts
  gender: female
# - role: tts
#   id: pytts
#   voice: 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech\\Voices\\Tokens\\TTS_MS_EN-US_ZIRA_11.0'
#   gender: female
# - role: tts
#   id: melo
#   config_filepath: null
#   model_filepath: null
#   speaker_id: EN-Default
#   device: cuda
#   language: EN
#   sdp_ratio: 0.8
#   noise_scale: 0.6
#   noise_scale_w: 0.8
#   speed: 1.0
# - role: tts
#   id: fish
#   model_id: c9198512a4164a18b11a3bf96e5c668f # ID da voz (Gigi ou padrão)
#   backend: speech-1.6
#   latency: normal

  # Audio filters
# - role: filter_audio
#   id: pitch
#   pitch_amount: 0
# - role: filter_audio
#   id: rvc
#   voice: my-voice-model
#   f0_up_key: 0
#   f0_method: rmvpe
#   f0_file: null
#   index_file: null
#   index_rate: 0.0
#   filter_radius: 3
#   resample_sr: 0
#   rms_mix_rate: 0
#   protect: 0.5

  # MCP LLM (can use any from T2T)
# - role: mcp
#   id: openai
#   base_url: https://api.openai.com/v1/
#   model: gpt-4o
#   temperature: 0.25
#   top_p: 0.9
#   presence_penalty: 0.2
#   frequency_penalty: 0.2

  # Embedding model
- role: embedding
  id: gemini
  model: models/gemini-embedding-2-preview

# Connect MCP servers, example commented
mcp: [] # Remove "[]" if adding servers
# - id: example_server
#   command: python
#   args: ["example_mcp_server.py"]
#   cwd: "path/to/server/directory"

# Prompter
prompter:
  instruction_prompt_filename: 'example.txt'
  character_prompt_filename: 'example.txt'
  scene_prompt_filename: 'example.txt'

  character_name: "Gigi a Sapeca"
  name_translations:
    "old name": "new name"
  history_length: 50

# Kobold
kobold_filepath: E:\\jaison-core\\models\\kobold\\koboldcpp_cu12.exe # must be absolute
kcpps_filepath: E:\\jaison-core\\models\\kobold\\save.kcpps # must be absolute

# Spacy NLP
spacy_model: null
